name: go_cdn_web_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ^3.5.1

dependencies: 
  get_cli: 1.8.0
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_form_builder: ^9.4.1
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  carousel_slider: ^5.0.0
  flutter_animate: ^4.5.0
  flutter_easyloading: ^3.0.5
  simple_icons: ^10.1.3
  visibility_detector: ^0.2.2
  dropdown_button2: ^2.0.4
  shared_preferences: ^2.0.6
  eva_icons_flutter: ^3.1.0
  video_player: ^2.5.1
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/head.mp4
